# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
User.create(username: "jason", email: "jason@jason.com", pic:"http://i.imgur.com/vk54xPh.jpg", password: 12345678, password_confirmation:12345678, bio: "My name is Jason, I was born and raised in Los Angeles.  As a youth I was heavily into soccer and music and was part of a rock band in the 5th grade where I was the singer and played the electric guitar. These days I enjoy mountain biking, fast import cars, skin diving/swimming, mixed martial arts, and soccer. I enjoy music and I probably couldn't live without it. My favorite genres of music are industrial metal, 80's music, and European Trance. I'm hoping to brush up on my singing skills and join a band within the next year or two since that's always been a dream of mine. I really bad problems sleeping and have had clinical insomnia since I was about 5. I've broken 11 bones in my body including breaking my arm in half 3 times. I'm not religious although I keep an open mind. I'm allergic to cucumbers and really hate bell peppers. I think dogs are truly man's best friend.", zipcode: "90638")
User.create(username: "melissa", email: "melissa@melissa.com", pic: "http://i.imgur.com/4gwJQJs.jpg", password: 12345678, password_confirmation: 12345678, bio: "Hi! My name is Sarah and I'm sure you can surmise the nickname coined from my last name. I grew up in Delaware and will likely stay in the area. So far as hobbies, I play golf, I dig expensive European cars (Aston Martins and Audis freaking rock), play some ice hockey and I love my guitars and guns. I have a penchant liking for dogs and am highly allergic to cats.", zipcode: "90210")
User.create(username: "john", email: "john@john.com", pic: "http://i.imgur.com/h64F8HR.jpg", password: 12345678, password_confirmation: 12345678, bio: "My name is John. I used to say I was mostly German but through some reveals about genealogical infidelity, I'm not even sure, and never will be. Suffice it to say I have a European background. Born and raised in a small town in Indiana where the fun thing to do was to drink out of my buddies tailgate. Not much changed in that respect. I attend Purdue University here in IN. Used to be full time, but grabbed a full time job and started going to shcool part time. This made me a 5th year senior in Computer Science, but I was able to pay *most* of my way thru so far. My day job is a Computer Systems Administrator and it is honestly the easiest big-boy job one could get and I love how relaxed and lazy it is.", zipcode: "90703")
User.create(username: "sarah", email: "sarah@sarah.com", pic: "http://i.imgur.com/qtZq40A.jpg", password: 12345678, password_confirmation: 12345678, bio: "Hi! My name is Sarah and I'm sure you can surmise the nickname coined from my last name. I grew up in Delaware and will likely stay in the area. So far as hobbies, I play golf, I dig expensive European cars (Aston Martins and Audis freaking rock), play some ice hockey and I love my guitars and guns. I have a penchant liking for dogs and am highly allergic to cats.", zipcode: "19711" )